### PR TITLE
Include Typescript sources in packages to support local debugging

### LINKED ISSUE #10: Debugging installed garment package is broken
## Issue Report

When I have garment installed locally, in order to debug, I have to delete the source map comments to debug the compiled JS files since the original TS files aren't included in the package.

(A clear and concise description of the issue)

## Expected Behavior

(Write out the expected behavior here.)
Either no map files are included, or the original TS files are included with the map files.

## Actual Behavior

(Write out what actually happened here.)
Here's an excerpt of my node_modules directory :

image

The bottom of each js file will have the correct url to the map file, however, because the TS files aren't included in node_modules, it won't be able to find them.  I'll get an error of could not find file in Chrome Node Inspector.

## Steps to Reproduce the Issue

(Write out detailed steps to reproduce the issue here.)
Install garment

## Proposal

Either
 

1.   Remove "sourceMap": true, from tsconfig.base.json (easier and low maintenance overhead, but not as user-friendly debugging experience), or 
2.   Include the ts files along with lib in every garment package (more maintenance overhead, but better debugging experience).  

I'd prefer 2 myself.

I can make the PR depending on which you decide, or include it in the PR I already have open if you'd prefer.

### PR DESCRIPTION
**Pull request by stephan-noel**
# Description

Includes the src directory in all packages which also included lib.

No unit tests added, as this is a functionality of the package installer itself.

Fixes #10

## How Has This Been Tested?

The following steps were done for both `@garment/cli` and `@garment/plugin-runner-ts`:

1. Use yarn pack in package directory
2. Install zip files resulting from yarn pack in a repo that uses garment.  Verify that src files are included in correct location upon installation.
3. Debug original TypeScript files in Chrome Node inspector.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added tests to cover my changes
- [x] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

**Comment by beshanoe** [comment]
After the discussion, I would rather strip all the map files when building for publishing. The code should still be readable enough to debug I believe

**Comment by luisvieiragmr** [comment]
Hey should we close this issue then? I'm actually not against publishing source files but I would avoid it if possible

**Comment by beshanoe** [comment]
it needs to be changed in order to build on CI without source maps, cause issue is still there

**Comment by stephan-noel** [comment]
Sorry guys, I've been a bit busy lately.  I can try to take care of this ASAP.

**Comment by stephan-noel** [comment]
This is giving me a lot more trouble than I expected.  The crux of the problem seems to be that currently `-- build` does NOT support mixing with other `tsc` flags.  There is a supposedly planned change in the future [as stated here](https://github.com/Microsoft/TypeScript/issues/25613), but I'm not sure when or if it will include `--sourceMap`.  

My plan was to introduce a `build:dev` command in `package.json` that would pass `--sourceMap`.

Other failed alternatives:
- Passing multiple config files with `tsc --build tsconfig.json tsconfig.dev.json`: Doesn't seem to be how multiple json files was meant to be used 
- Create a `tsconfig.dev.json` file which extends `tsconfig.json`:  Cannot do this, `references` are not inherited with `extends`
- Create a separate file `tsconfig.dev.json` which duplicates all references in `tsconfig.json` and add `compilerOptions: { sourceMap: true } to it`:  Referenced projects ignored this option, they seem to only respect what they directly extend from.

Other alternatives not investigated:

- Use the TypeScript compiler API for incremental builds (seems a bit much) 

Successful but unmaintainable alternative:
- We place a `tsconfig.dev.json` file in each project that has `sourceMap` set to true, extends the project-specific `tsconfig.json` and duplicates the references in the project-specific `tsconfig.json` since they are not inherited.  We create another solution file at the top level named `tsconfig.dev.json` whose paths instead of pointing to the project, point to the project-level `tsconfig.dev.json`.  With this solution we have duplication at both the top level and the project level.

Maybe I'm missing something obvious.  @beshanoe, @luisvieiragmr, any thoughts on a possible strategy to proceed with?

**Comment by beshanoe** [comment]
Wow that was really unexpected :D Thanks for the thorough investigation of alternatives. To be honest I don't see any good alternative here except turning off sourcemaps whatsoever. I'm working now on building garment with garment and it seems to be the best alternative cause we don't need to use references and can pass any config with a flag

**Comment by stephan-noel** [comment]
Yeaa it was pretty frustrating 😄.  Yeaa, building garment with garment seems like the best approach.  What do you think I should do with this issue?  Close, or leave it until we can try implementing it with garment building itself?

**Comment by beshanoe** [comment]
@stephan-noel now I'm in the process of building it with garment but I already found issues there so I`m on it, if I manage to finish it this week, we'll decide what to do then

**Comment by beshanoe** [comment]
should be fixed by https://github.com/Farfetch/garment/pull/20 so Im closing this one

**Pull request closed without merging**
